# model
model: JointMattingParsing
loss: JointMattingParsingLoss
backbone: mobilenetv3_large
phase: end2end
# solver
num_epochs: 200
adj_epochs: 180
beg_lr: 0.001
end_lr: 0.000001
batch_size: 24
momentum: 0.9
weight_decay: 0.0001
# training
num_workers: 6
pin_memory: True
benchmark: True
# data-set
dataset: HumanSegmentation
dataset_yaml: config/dataset/human-dataset.yaml
num_classes: 3
crop_height: 512
crop_width: 512
# misc
note_info: baseline for mobilenetv3 with 512x512
save_epoch: 100
save_path: save/human/knight-03-mobilenetv3-joint
backbone_pretrain: /home/knight/Workspace/xhx/pretrain/mobilenet_v3_large-8738ca79.pth
pretrain: 
prefix_name: segnet
device: '0'